/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesBsbaRouteImport } from './routes/courses/Bsba'

const HistoryLazyRouteImport = createFileRoute('/History')()

const HistoryLazyRoute = HistoryLazyRouteImport.update({
  id: '/History',
  path: '/History',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/History.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesBsbaRoute = CoursesBsbaRouteImport.update({
  id: '/courses/Bsba',
  path: '/courses/Bsba',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/History': typeof HistoryLazyRoute
  '/courses/Bsba': typeof CoursesBsbaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/History': typeof HistoryLazyRoute
  '/courses/Bsba': typeof CoursesBsbaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/History': typeof HistoryLazyRoute
  '/courses/Bsba': typeof CoursesBsbaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/History' | '/courses/Bsba'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/History' | '/courses/Bsba'
  id: '__root__' | '/' | '/History' | '/courses/Bsba'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryLazyRoute: typeof HistoryLazyRoute
  CoursesBsbaRoute: typeof CoursesBsbaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/History': {
      id: '/History'
      path: '/History'
      fullPath: '/History'
      preLoaderRoute: typeof HistoryLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/Bsba': {
      id: '/courses/Bsba'
      path: '/courses/Bsba'
      fullPath: '/courses/Bsba'
      preLoaderRoute: typeof CoursesBsbaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryLazyRoute: HistoryLazyRoute,
  CoursesBsbaRoute: CoursesBsbaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
